### ISSUE TITLE
Change SampleRate

### ISSUE THREAD

**Issue by 9acca9** [yzyhk904/USB_SampleRate_Changer#18]
Hi.
This is not specific for Usb sound. 
I have a Qobuz subscription and want to use the android app from Qobuz, BUT, using another app like Airmusic to get the audio and send that to a upnp server (that have a good DAC).
I already make this but, im only getting in the DAC 24bit 44000khz. 
I will like 192khz or at least 92000. 
Did you know if i can change the rate of the audio in some manner.
Thanks for your help.

**Comment by yzyhk904** [comment]
The Android standard capture and the AirMusic proprietary feature use a remote submix audio module that can handle 44.1kHz 16bit and 48kHz 16bit only. You cannot do that.

However, you can convert any format to 44.1kHz 16bit without distortion if you use "extras/change-resampling-quality.sh". Hires formats don't have any advantage over 44.1kHz 16bit format under low jitter situations, so I recommend to use "extras/jitter-reducer.sh" at the same time.
