### ISSUE TITLE
Possible to "deamplify" audio coming from the headphone jack? 

### ISSUE THREAD

**Issue by CastanaEddd** [yzyhk904/USB_SampleRate_Changer#20]
Hey, I've been having this issue where the minimum volume coming out from my headphone jack while plugged in with iems is way too loud for a reasonable listening experience. Tried using a couple of system wide audio fx solutions (JamesDSP and V4A) which works fine until opening certain applications and games (would also like to avoid using this as a solution if possible). Attempting to increase the number of volume steps to anything larger then 30 leads to some of the steps to have no effect on the volume.

Had this issue for a while now and it's the only thing preventing me from using my iems on my phone any suggestions would be greatly appreciated.

**Comment by yzyhk904** [comment]
I don't know how you changed the number of volume steps, but try ["audio-misc-settings"](https://github.com/Magisk-Modules-Alt-Repo/audio-misc-settings) of mine magisk module which increases the number of volume steps to be 100. Some stock ROMs cannot change the number of volume steps, but you will change it after installing a popular custom ROM.

I've never experienced such a situation with this magisk module even when using very loud DACs, e.g., iBasso stick DACs without their proprietary volume app.
