### ISSUE TITLE
Support google pixel 8

### ISSUE THREAD

**Issue by g1nt0** [yzyhk904/USB_SampleRate_Changer#26]
pls add support google pixel 8.

**Comment by nokia5700black** [comment]
pixel 8 pro 

ro.board.platform = zuma

not cs**

**Comment by g1nt0** [comment]
https://github.com/yzyhk904/USB_SampleRate_Changer/pull/27

**Comment by yzyhk904** [comment]
I've already updated separately.
Thanks for your comment!

**Comment by yzyhk904** [comment]
I don't have Pixel 8's and cannot optimize the USB (transfer) period for Pixel 8's for reducing significant jitter.
Please tell me your best USB period for Pixel 8 Pro.

I set temporally 2250 usec for Pixel 8's the same as for Pixel 6 & 7's. You can change the period on the fly by "extras/change-usb-period.sh" after installing "audio-misc-settings" magisk module.

I feel Tensor devices are very sensitive to the period (default value 5000usec makes too large jitter for music lovers!).

**Comment by g1nt0** [comment]
@yzyhk904 please tell me how I can check jitter, I can’t hear the difference between 1000 and 10000, do I need some kind of test audio file?

**Comment by yzyhk904** [comment]
1. I doubt your changing attempt succeeded. Pixel 6's produce abnormal noise when replaying music through a USB DAC if the period set to be 1000. Probably larger than 1500usec is needed for normal replay.

Pixel 8's use an offloading USB driver "/vendor/lib64/audio_usb_aoc.so" to output to USB DAC's, but the driver has a bug when handling the USB period changing. For avoiding the bug, you need "audio-misc-settings.zip" or "hifi-maximizer-mod.zip". You can see period size changing by "extras/alsa-hw-params.sh" only during replaying music if it succeeds.

If you set the period p (usec) and sampling rate r (Hz), then you will see,

rate: r
period_size: s

where s = r * p / 1000000.

For example, 48000Hz * 5000usec / 1000000 = 240 samples

2. Do you installed "audio-jitter-silencer.zip"? "Doze" and battery monitoring on Android makes very large jitter. You can avoid this jitter by the module.

3. Use "hifi-maximizer.zip" to reduce other jitter significantly for focusing the USB period jitter.

4. If you cannot hear the difference through, select live recording tracks and focus edges of base drums and soprano voices. You could hear fogish sound effect around them produced by the jitter.

**Comment by g1nt0** [comment]
Sorry, I tried it a couple of times both through the script and having registered it in the module in advance... I don’t hear the difference between 1k, 2k and 5k (maybe once every half hour, something gets chewed up for a split second, as if there was some kind of out of sync and that’s it(

**Comment by yzyhk904** [comment]
Have you ever been using [Audio Jitter Silencer](https://github.com/Magisk-Modules-Alt-Repo/audio-jitter-silencer)? Probably other jitters on Pixel 8 are too large for you to hear the difference.

If you like, try the module to reduce other jitters significantly.
