### ISSUE TITLE
Will the recent changes of this app to Pixel 7 be integrated into the Hifi Maximizer mod asap?

### ISSUE THREAD

**Issue by HarriBuh** [yzyhk904/USB_SampleRate_Changer#31]
```
Fixed Pixel7's default USB sample rate limiter (96kHz -> 192kHz) for adapting to a recent change

```

I'm using your other mod, Hifi Maximizer, and since your latest patch looks quite useful..

**Comment by yzyhk904** [comment]
Do you have any issue on Pixel7? 

As Hifi Maximizer has already been optimized for Pixel 6's, 7's and 8's especially on demonstration purpose,  they do output 44.1kHz and HIRES tracks at 192kHz & 32bit (signed integer) mode through USB DAC's now by default.

FYI, Pixel 7's have the limiter of the USB offload driver at 192kHz now on stock ROM's, and Pixel 8's also have from the beginning. However Pixel 6'a have had at 96kHz till now.

USB_SampleRate_Changer has only changed for Pixel 7's not to warn "installing USB Samplerate Unlocker" for 192kHz output selection.
