### ISSUE TITLE
chcon: failed to change context of '/data/local/tmp/audio_conf_generated.xml' to ‘u:object_r:vendor_configs_file:s0

### ISSUE THREAD

**Issue by a6886126** [yzyhk904/USB_SampleRate_Changer#32]
![Screenshot_2024-06-15-02-55-49-887_bin mt plus](https://github.com/yzyhk904/USB_SampleRate_Changer/assets/61091205/ceccc71c-074a-4812-bb86-00acfaddc981)
sdcard su
# sdcard sh /sdcard/USB_SampleRate_Changer/USB_SampleRate_Changer.sh --bypass-offload-safer 44k 16
chcon: failed to change context of '/data/local/tmp/audio_conf_generated.xml' to ‘u:object_r:vendor_configs_file:s0’: Operation not supported on transport endpoint
# sdcard

**Comment by yzyhk904** [comment]
I've never heard of this error till now. If your "/data" partition doesn't support SELinux context and you want to use this script anyhow, change the SELinux mode to be "permissive". Then you could use this script probably with the same error message. Please ignore the message.

Try "extras/jitter-reducer.sh" with "--selinux" option.
