### ISSUE TITLE
Pixel 9 pro xl ("/vendor/etc/audio_policy_configuration.xml") doesn't exist!

### ISSUE THREAD

**Issue by g1nt0** [yzyhk904/USB_SampleRate_Changer#34]
SampleRate_Changer_44_32.sh; exit &>/dev/null             <
overlaying target ("/vendor/etc/audio_policy_configuration.xml") doesn't exist!

[Process completed (error 1) - press Enter]

**Comment by yzyhk904** [comment]
What's the SampleRate_Changer_44_32.sh? Try scripts under "Usage_Samples".

**Comment by g1nt0** [comment]
same(

USB/USB_48k_24.sh; exit &>/dev/null            <
overlaying target ("/vendor/etc/audio_policy_configuration.xml") doesn't exist!

[Process completed (error 1) - press Enter]

**Comment by g1nt0** [comment]
:/data/data/com.termux/files/home # setenforce 0
:/data/data/com.termux/files/home # getenforce
Permissive
same result(

~ $ su
:/data/data/com.termux/files/home # ls -lZ /vendor/et>
ls: /vendor/etc/audio_policy_configuration.xml: No such file or directory
1|:/data/data/com.termux/files/home #

**Comment by yzyhk904** [comment]
The file must be there, and I think it may not happen.

I guess "Termax" might do something wrong. Please use Mixplorer (free version) to execute "Usage_Samples". See README.

**Comment by g1nt0** [comment]
![Screenshot_20241031-172024](https://github.com/user-attachments/assets/c10ab31e-c50d-4b1a-8ab1-f3352cb6055f)
this file is not here

**Comment by g1nt0** [comment]
I can't find this file anywhere at all(

**Comment by g1nt0** [comment]
![Screenshot_20241031-172943](https://github.com/user-attachments/assets/e80abcb5-9d14-4cd9-b7d4-3ee941b9ca43)

**Comment by g1nt0** [comment]
@yzyhk904 
`adb shell
su
find / -print > `/sdcard/full_catalog.txt`
![image](https://github.com/user-attachments/assets/2a9d1ad2-bf9c-4c4b-9717-0ca29571f504)

**Comment by yzyhk904** [comment]
I researched the audio system of Pixel9, and found it had only AIDL, but not HIDL (audio policy configuration by XML). This script cannot run on AIDL only devices like Pixel 9 series (built for their AIDL only configurations).

I will add codes for excepting Pixel 9 series and other AIDL only devices, and add info in README.

**Comment by g1nt0** [comment]
could this change with software updates or if the device was released like this right away, will it be the same in a row?

**Comment by yzyhk904** [comment]
Same. This script can support only HIDL based devices. If there is a compatibility command converting HIDL to AIDL, I may support AIDL devices future.

By the way, there is a build option in Pixel 9 series firmware sources for HIDL instead of AIDL. If you build the firmware for HIDL, you could use this script.
