### ISSUE TITLE
Recent AIDL only devices are not supported!🥺🥺

### ISSUE THREAD

**Issue by 2605406346** [yzyhk904/USB_SampleRate_Changer#35]
I encountered an issue when using the terminal emulator in MT Manager to execute sh /sdcard/USB_SampleRate_Changer/USB_SampleRate_Changer.sh --bypass-offload-safer 384k 32. The error message was: "Recent AIDL only devices are not supported!"
I have installed USB Samplerate Unlocker 1.5.7 on Magisk 28.
My device is a OnePlus 13 running Android 15.

**Comment by yzyhk904** [comment]
That's it! It isn't any error. This script cannot support AIDL only (having no HIDL functions) devices like Pixel 9 series.
