### ISSUE TITLE
galaxy S10+  audio mod

### ISSUE THREAD

**Issue by UrbanDesimator** [yzyhk904/USB_SampleRate_Changer#4]
Hi I'm blown away by the difference in sound after using change-resampling-quality.sh with audio at 48kHz with 194dB 480 100%. I was impressed with S10 sound as the amplifier chip is very low distortion, with my studio spec headphones the change in the sound stage is huge at 194dB 480 100% compared to default settings which produced a lot of audable aliasing. 
Currently viper4android fx V2.7.21 the default after install is  legacy mode is enabled to fully activate viper4. I ran the above script with --status first to log my original values then with 194dB 480 100. The settings were changed  and confirmed with --status, after the change I found legacy mode in viper4 was not default for activation. Is this what you would expect or do you think it's a setup/install issue of my mods. 
Current setup is thunderstormS kernel with magisk SA root, Musicfx removed, Viper4, installed in magisk 1st but not driver, 2nd AML installed, then Viper4 driver then it reboots, 3rd ainur narsil set to 48kHz 32ohm MIMPEDANCE, hi pass filter on reboot, 4th audio compatability patch using new patch mode deep buff remove, notification listener library removed. The files attached are all post running the script, if you need them from prior I can upload.
Thank you so much for making the scripts.
UrbanDesimator

**Comment by yzyhk904** [comment]
Did you use `jitter-reducer.sh` with "--effect" option or Magisk module "audio-misc-settings" or hifi-maximizer-mod"? If so, those disabled AudioFlinger's effects framework which viper4 used. Then, try `jitter-reducer.sh ++effect` command. `change-resampling-quality.sh` changes only "ro.audio.resampler.psd.*" properties that never affect equalizers.

By the way, I think your best settings (for 3.5mm jack?) are 44.1kHz & 32bit without DRC by `USB_SampleRate_Changer.sh`. If you prefer 48kHz, perhaps `change-resampling-quality.sh 160 480 91` is the best.
