### ISSUE TITLE
Sorry as a noob I want to ask is this meaning that we remove the limited of the android src?

### ISSUE THREAD

**Issue by WaytrueDeng** [yzyhk904/USB_SampleRate_Changer#5]
thanks for your hardwork

**Comment by yzyhk904** [comment]
You can change the sample rate of USB DAC's and possibly 3.5mm jack on your device on the fly for avoiding SRC distortion. A 3.5mm jack on MTK devices is often fixed at 44.1kHz or 48kHz and its sample rate cannot be changed. You can also avoid DRC (compression) on Snapdragon SoC devices. 

Moreover,  you can avoid a digital filter of the OS mixer (AudioFlinger) for 1:1 ratio resampling by using "extras/change_resampling_quality.sh".
