### ISSUE TITLE
Unzip Error: Trying to install module 

### ISSUE THREAD

**Issue by Harleythetech** [yzyhk904/USB_SampleRate_Changer#7]
Somehow your file won't install on magisks 

Q: are you running the latest magisks:
A: Yes

Q: What device are you using and what OS?
A: Sony Xperia Z5 (Sumire DSDS) - Lineage OS 18.1 (11-R)

Q: DAC?
A: Avani ALC5686 384kHz

Error is on the title :D thanks!

**Comment by yzyhk904** [comment]
This tool isn't a Magisk module at all, but is a collection of shell scripts requiring Magisk su or phh SuperSu. Each released zip file is just an archive of such shell scripts and their data.

You can unzip it on the internal storage of your device and execute unziped shell scripts with Magisk su.
